"""Exclusão lógica de usuários

Revision ID: 273b25b4fef6
Revises: 5ac7a57fff91
Create Date: 2025-06-24 10:05:02.959215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '273b25b4fef6'
down_revision: Union[str, Sequence[str], None] = '5ac7a57fff91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'status',
               existing_type=mysql.ENUM('ATIVO', 'INATIVO'),
               type_=sa.Enum('INATIVO', 'ATIVO', name='status', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'status',
               existing_type=sa.Enum('INATIVO', 'ATIVO', name='status', native_enum=False),
               type_=mysql.ENUM('ATIVO', 'INATIVO'),
               existing_nullable=False)
    # ### end Alembic commands ###
