"""Ajustando coluna de filiais

Revision ID: 5ac7a57fff91
Revises: 195ebc81393a
Create Date: 2025-06-21 10:28:02.922644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5ac7a57fff91'
down_revision: Union[str, Sequence[str], None] = '195ebc81393a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('filiais', sa.JSON(), nullable=False))
    op.drop_column('usuarios', 'filais')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('filais', mysql.JSON(), nullable=False))
    op.drop_column('usuarios', 'filiais')
    # ### end Alembic commands ###
