"""Apenas CPF como Unique

Revision ID: ee24d9090395
Revises: 273b25b4fef6
Create Date: 2025-07-02 14:29:05.135813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee24d9090395'
down_revision: Union[str, Sequence[str], None] = '273b25b4fef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('nomeUsuario'), table_name='usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('nomeUsuario'), 'usuarios', ['nomeUsuario'], unique=True)
    # ### end Alembic commands ###
